spring:
  application:
    name: data-consumer
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  data:
    mongodb:
      host: localhost
      port: 27018
      database: airdata_db

server:
  port: 9002                    # 指定该Eureka实例的端口

eureka:
  instance:
    hostname: data-consumer         # 指定该Eureka实例的主机名
  client:
    serviceUrl:
      defaultZone: http://service-registry:8761/eureka/
